auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("", include("quiz.urls")),
]

users/urls.py
from django.urls import path
from .views import Register, loginView, LogoutView, UserDetailView, UserListView
from .views import home,register_view,home_content,login_view,  info_page, HomeAdminView,add_user,DeleteUser,user_detail,user_update_view,DashboardView, MyPageView

urlpatterns = [
    path("register/", Register.as_view(), name="register"),
    path("register-view/", register_view, name="register_view"),
    path("login/", loginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view() , name="logout"),
    path("user/<int:pk>/", UserDetailView.as_view(), name="userdetail" ),
    path("user_detail/<int:pk>/", user_detail, name="user_detail"),
    path("user/", UserListView.as_view(), name= 'user'),
    path("", home, name="home"),
    path("home-content/", home_content, name="home_content"),
    path("login-view/", login_view, name="login_view"),
    path('info/', info_page, name='info_page'),
    path("home_admin/",HomeAdminView.as_view(), name = "home_admin" ),
    path("add_user/",add_user,name = "add_user"),
    path('delete_user/<int:pk>/', DeleteUser.as_view(), name='delete_user'),
    path('update-user/<int:user_id>/', user_update_view, name='user_update'),
    path("dashboard/",DashboardView.as_view(), name= "dashboard"),
    path("mypage/",MyPageView.as_view(),name = "my_page")

    

]

quiz/models.py
from django.db import models
from users.models import User
from django.conf import settings
class Topic(models.Model):
    name = models.CharField(max_length=255)
    User = settings.AUTH_USER_MODEL
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=3)
    def __str__(self):
        return self.name

class Question(models.Model):
    text = models.CharField(max_length=255)
    default_topic_id = 1  # ID của chủ đề mặc định đã tồn tại trong cơ sở dữ liệu
    topic = models.ForeignKey(Topic, related_name='questions', on_delete=models.CASCADE, default=default_topic_id)

    def __str__(self):
        return self.text

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

users/models.py
from django.db import models


# Create your models here.  
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.CharField(max_length=255, unique=True)
    username = models.CharField(max_length=150, unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

users/views.py
from django.shortcuts import render, redirect
from .serializers import UserSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.exceptions import AuthenticationFailed
from users.models import User
from rest_framework import status
from django.urls import reverse
from django.contrib import messages
from quiz.models import Topic,Question
from django.shortcuts import redirect
from users.forms import UserForm
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
import requests
from django.contrib.auth import login,logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, user_passes_test

class Register(APIView):
    def post(self,request):
        serializer = UserSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        messages.success(request, 'Account created successfully')
        # sau khi tạo tài khoản xong thì load lại trang đang ở
        return redirect(reverse('login_view'))




class loginView(APIView):
    def post(self, request):
        email = request.data.get('email')
        password = request.data.get('password')

        # Thực hiện xác thực người dùng
        user = User.objects.filter(email=email).first()
        if user is None:
            raise AuthenticationFailed('User not found')
        if not user.check_password(password):
            raise AuthenticationFailed('Incorrect password')
        login(request, user)
        # Kiểm tra nếu người dùng là admin
        if user.is_staff:
            # Nếu là admin, chuyển hướng đến trang homeadmin
            return redirect('home_admin')
        else:
            # Nếu không phải admin, chuyển hướng đến trang my_page
            return redirect('my_page')


       
    

class LogoutView(APIView):
    def post(self,request):
        logout(request)
        response = Response()
        response.delete_cookie('jwt')
        response.data = {
            'message': ' logout success'
        }
        return render(request,'login.html')
class UserDetailView(APIView):
    def get(self,request,pk):
        user = User.objects.filter(id=pk).first()
        if user is None:
            return Response({"error": "User not found"}, status=status.HTTP_404_NOT_FOUND)
        serializer = UserSerializer(user)
        return Response(serializer.data)
    def put(self,request,pk):   
        user = User.objects.filter(id=pk).first()
        if user is None:
            return Response({"error": "User not found"}, status=status.HTTP_404_NOT_FOUND)
        serializer = UserSerializer(user, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    def delete(self,request,pk):
        user = User.objects.filter(id=pk).first()
        if user is None:
            return Response({"error": "User not found"}, status=status.HTTP_404_NOT_FOUND)
        user.delete()
        return Response({"message": "User deleted"}, status=status.HTTP_204_NO_CONTENT)

    def update(self, request, pk):
        try:
            user = User.objects.get(id=pk)
        except User.DoesNotExist:
            return Response({"error": "User not found"}, status=status.HTTP_404_NOT_FOUND)

        # Cập nhật dữ liệu người dùng từ các tham số truyền vào
        if 'username' in request.data:
            user.username = request.data['username']
        if 'email' in request.data:
            user.email = request.data['email']
        # Thêm các trường khác cần cập nhật nếu có

        # Lưu lại thay đổi
        user.save()

        # Tạo serializer với dữ liệu người dùng đã được cập nhật
        serializer = UserSerializer(user)

        return Response(serializer.data)


class UserListView(APIView):
    def get(self, request):
        users = User.objects.all()
        serializer = UserSerializer(users, many=True)
        return Response(serializer.data)
    

def home(request):
    return render(request, 'home.html')
def register_view(request):
    return render(request, 'register.html')
def home_content(request):
    return render(request, 'quiz.html')
def login_view(request):
    return render(request, 'login.html')

def info_page(request):
    return render(request, 'info.html')



class DeleteUser(APIView):
    def delete(self, request, pk):
        user = User.objects.filter(id=pk).first()
        if user is None:
            return Response({"error": "User not found"}, status=status.HTTP_404_NOT_FOUND)
        user.delete()
        return Response({"success": "User deleted successfully"}, status=status.HTTP_204_NO_CONTENT)



def add_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'User added successfully')
            return redirect('home_admin')  # Chuyển hướng đến trang homeadmin
    else:
        form = UserForm()
    return render(request, 'add_user.html', {'form': form})
def user_detail(request, pk):
    # Gọi REST API để lấy thông tin chi tiết của người dùng
    response = requests.get(f'http://127.0.0.1:8000/user/{pk}/')
    user_data = response.json()
    # Truyền dữ liệu vào template và render trang
    return render(request, 'user_detail.html', {'user_data': user_data})


def user_update_view(request, user_id):
    # Xử lý yêu cầu GET để hiển thị form cập nhật thông tin người dùng
    if request.method == 'GET':
        # Gửi yêu cầu REST API để lấy thông tin chi tiết của người dùng
        response = requests.get(f'http://127.0.0.1:8000/user/{user_id}/')
        if response.status_code == 200:
            user_data = response.json()
            return render(request, 'user_update.html', {'user_data': user_data})
        else:
            # Xử lý trường hợp không tìm thấy người dùng
            messages.error(request, 'User not found')
            return redirect('home_admin')
    # Xử lý yêu cầu POST để cập nhật thông tin người dùng
    elif request.method == 'POST':
        # Lấy dữ liệu từ form gửi lên
        updated_data = request.POST
        # Gửi yêu cầu REST API để cập nhật thông tin người dùng
        response = requests.put(f'http://127.0.0.1:8000/user/{user_id}/', data=updated_data)
        if response.status_code == 200:
            messages.success(request, 'User information updated successfully')
            return redirect('home_admin')
        else:
            # Xử lý trường hợp cập nhật thất bại
            messages.error(request, 'Failed to update user information')
            return redirect('home_admin')    

class HomeAdminView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request):
        users = User.objects.all()
        return render(request, 'home_admin.html', {'users': users})
class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #lấy ra tổng user và tổng topic tổng câu hỏi
        total_user = User.objects.all().count()
        total_topic = Topic.objects.all().count()
        total_questions = Question.objects.all().count()

        context['total_user'] = total_user
        context['total_topic'] = total_topic
        context['total_questions'] = total_questions

        return context
class MyPageView(LoginRequiredMixin, TemplateView):
    template_name = 'mypage.html'
    
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        topics = Topic.objects.all()
        for topic in topics:
            topic.question_count = topic.questions.count()
            topic.created_by = topic.user.username
        context['topics'] = topics
        context['current_user'] = current_user.username
        return context

users/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles_dashboard.css' %}">
</head>

<body>
    <!-- START NAVBAR -->

    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Admin</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
                aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">
                        Dark offcanvas
                    </h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'my_page' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Quản lý
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                                <li><a class="dropdown-item" href="{% url 'home_admin' %}">User</a></li>
                                <li><a class="dropdown-item" href="{% url 'question_manage' %}">Qusetions</a></li>
                                <li><a class="dropdown-item" href="{% url 'topic_manage' %}">Topic</a></li>
                            </ul>

                        </li>
                        <li>
                            <hr class="divider">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="logout()">Đăng xuất</a>
                            <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                                {% csrf_token %}
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <!-- End navbar -->
    <div class="dashboard-container">
        <div class="title">
            Analysis Dashboard
        </div>
        <div class="content">
            <div class="c-left">
                <div class="child">
                    <span class="text-1">Total user</span>
                    <span class="text-2">{{total_user}}</span>
                </div>
                <div class="child">
                    <span class="text-1">Total Topic</span>
                    <span class="text-2">{{total_topic}}</span>
                </div>
                <div class="child">
                    <span class="text-1">Total Questions</span>
                    <span class="text-2">{{total_questions}}</span>
                </div>
                <div class="child">
                    <span class="text-1">Total Answers</span>
                    <span class="text-2">169</span>
                </div>
            </div>
            <div class="c-right">
                <canvas id="myChart" width="800" height="400"></canvas>
            </div>
        </div>

        <div class="chart-pie">
            <canvas id="myPieChart"></canvas>

        </div>

    </div>

    <script>
        // Lấy tham chiếu đến thẻ canvas
        var ctx = document.getElementById('myPieChart').getContext('2d');

        // Tạo dữ liệu cho biểu đồ
        var data = {
            labels: ['Câu đúng', 'Câu sai'],
            datasets: [{
                data: [30, 10], // Số câu đúng và câu sai
                backgroundColor: ['#36A2EB', '#FF6384'], // Màu cho từng phần
                hoverBackgroundColor: ['#36A2EB', '#FF6384']
            }]
        };

        // Tạo biểu đồ hình tròn
        var myPieChart = new Chart(ctx, {
            type: 'pie',
            data: data,
            options: {
                responsive: true,
                maintainAspectRatio: false
            }
        });

        // Lấy thẻ canvas
        var ctx = document.getElementById('myChart').getContext('2d');

        // Tạo dữ liệu biểu đồ
        var data = {
            labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
            datasets: [{
                label: 'My First Dataset',
                data: [12, 19, 3, 5, 2, 3],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        };

        // Tạo biểu đồ cột
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: data,
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

users/templates/info.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thông tin</title>
    <!-- Thêm các tài nguyên CSS nếu cần -->
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        p {
            line-height: 1.6;
            color: #555;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Xin chào!</h1>
        <p>Đây là trang web quiz được thực hiện bởi nhóm 17.</p>
    </div>
</body>

</html>

users/templates/login.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark ">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register_view' %}">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- content -->
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    <h1 style="margin-left: 385px; padding: 50px 0px;">Login</h1>
    <div class="col-md-6 offset-md-3 ">

        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" name="email" required>
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" name="password" required>
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

users/templates/mypage.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Page</title>
    <link rel="stylesheet" href="{% static 'css/styles_mypage.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <header>
        <h2><a href="#" class="logo">Quizlet</a></h2>
        <div class="search-bar">
            <input type="text" placeholder="Tìm kiếm...">
            <i class="fa-solid fa-magnifying-glass"></i>
        </div>
        <div class="navigation">
            <a href="#" onclick="showLibrary()">Thư viện</a>
            <a href="{% url 'question_list' %}">Chủ đề</a>
            <a href="{% url 'info_page' %}">Liên hệ</a>
            <a href="{% url 'user' %}">Tài khoản</a>
            <li class="nav-item dropdown">
                <button class="btn btn-dark" data-bs-toggle="dropdown" aria-expanded="false">
                    T
                </button>
                <ul class=" dropdown-menu dropdown-menu-white">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#" onclick="logout()">Đăng Xuất</a></li>
                </ul>
            </li>
            <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                {% csrf_token %}
            </form>
            <div id="libraryItems" class="library-items">
                <a href="#">Lớp</a>
                <a href="#">Học phần</a>
                <a href="#">Thư mục</a>
            </div>
        </div>
    </header>
    <div class="content">
        <h1>Xin chào, {{current_user}}</h1>
        <h1>Nội     dung</h1>
    </div>
    <div class="container">
        <div class="box-wrapper">
            {% for topic in topics %}
            <div class="box">
                <div class="title"><a href="{% url 'start_quiz' topic.id %}">{{ topic.name }}</a></div>
                {% if topic.question_count %}
                <div class="description-box">
                    <div class="description"><span>({{ topic.question_count }} questions)</span></div>
                </div>
                {% endif %}
                <div class="SetPreviewCard-creator"><span>{{ topic.created_by }}</span></div>
            </div>
            {% endfor %}
        </div>
        <button class="prev-btn">&lt;</button>
        <button class="next-btn">&gt;</button>
    </div>
    <div class="create-question-box">
        <h3>Tạo câu hỏi</h3>
        <a href="{% url 'add_question' %}" class="create-question-btn">Tạo mới</a>
        <a href="{% url 'add_question_csv' %}" class="create-question-btn">Thêm bằng file csv</a>
    </div>


    <div class="content-6">
        <div class="content-item">
            <h4>Giới thiệu</h4>
            <a href="">
                <span>Giới thiệu về Quizlet</span>
            </a>
            <a href="">
                <span>Tuyển dụng</span>
            </a>
            <a href="">
                <span>Quảng cáo trên Quizlet</span>
            </a>
            <a href="">
                <span>Tải ứng dụng</span>
            </a>
        </div>
        <div class="content-item">
            <h4>Dành cho học sinh</h4>
            <a href="">
                <span>Thẻ ghi nhớ</span>
            </a>
            <a href="">
                <span>Kiểm tra</span>
            </a>
            <a href="">
                <span>Học</span>
            </a>
            <a href="">
                <span>Lời giải</span>
            </a>
            <a href="">
                <span>Q-Chat: gia sư AI của bạn</span>
            </a>
            <a href="">
                <span>Lặp lại ngắt quãng</span>
            </a>
            <a href="">
                <span>Modern Learning Lab</span>
            </a>
            <a href="">
                <span>Quizlet Plus</span>
            </a>
        </div>
        <div class="content-item">
            <h4>Dành cho giáo viên</h4>
            <a href="">
                <span>Live</span>
            </a>
            <a href="">
                <span>Cột mốc</span>
            </a>
            <a href="">
                <span>Blog</span>
            </a>
            <a href="">
                <span>Quizlet Plus cho giáo viên</span>
            </a>
        </div>
        <div class="content-item">
            <h4>Tài nguyên</h4>
            <a href="">
                <span>Trung tâm hỗ trợ
                </span>
            </a>
            <a href="">
                <span>Đăng ký</span>
            </a>
            <a href="">
                <span>Quy tắc danh dự</span>
            </a>
            <a href="">
                <span>Nguyên tắc cộng đồng</span>
            </a>
            <a href="">
                <span> Quyền riêng tư</span>
            </a>
            <a href="">
                <span> Điều khoản</span>
            </a>
            <a href="">
                <span> Chính sách quảng cáo và cookie</span>
            </a>
            <a href="">
                <span> Quizlet cho trường học</span>
            </a>

        </div>
        <div class="content-item">
            <h4>Ngôn ngữ</h4>
            <a href="">
                <span></span>
            </a>
        </div>
    </div>
    <div class="footer">

        <div class="media-icons">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-linkedin-in"></i></a>
        </div>

        <script src="{% static 'js/script_mypage.js' %}"></script>
</body>

</html>

users/templates/question_detail.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>Question Detail</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>

<body>
    <h1>Question Detail</h1>
    <h2>{{ question.text }}</h2>
    <ul>
        {% for choice in question.choices.all %}
        {% if choice.is_correct %}
        <li class="correct-answer">{{ choice.text }}</li>
        {% else %}
        <li>{{ choice.text }}</li>
        {% endif %}
        {% endfor %}
    </ul>
</body>

</html>

users/templates/user_detail.html
<!-- user_detail.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Detail</title>
</head>

<body>
    <h1>User Detail</h1>
    <p><strong>ID:</strong> {{ user_data.id }}</p>
    <p><strong>Username:</strong> {{ user_data.username }}</p>
    <p><strong>Email:</strong> {{ user_data.email }}</p>
</body>

</html>